services:
  optionspatternvalidation.api:
    image: ${DOCKER_REGISTRY-}optionspatternvalidationapi
    container_name: options-pattern-validation-api
    build:
      context: .
      dockerfile: src/OptionsPatternValidation.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
